config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'application#home'

  get '/secret', to: 'application#secret', as: 'secret'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home]
  def home

  end

  def secret

  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :admin])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<h1>This is the home page</h1>

<% if current_user %>

<ul>
  <li><%= current_user.first_name %></li>
  <li><%= current_user.last_name %></li>
  <li><%= current_user.encrypted_password %></li>
  <li><%= current_user.created_at %></li>
  <li><%= current_user.current_sign_in_at %></li>

</ul>


<% end %>

<% if current_user && current_user.admin %>
  <h2>you ARE an ADMIN!!!</h2>
<% end %>

app/views/application/secret.html.erb
<h1>Shhh don't tell anyone about this page</h1>

<h3>If you tell anyone bad things will happen!</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrDeviseAppPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home Page', '/' %>
    <%= link_to 'Secret', secret_path %>
    <%= link_to 'Sign Up', new_user_registration_path  %>

    <%= link_to 'Sign In', new_user_session_path  %>

    <% if current_user %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %>
    <%= link_to 'Edit/Delete Account', edit_user_registration_path %>


    <% end %>
    <%= yield %>
  </body>
</html>